Repository poetapp/frost-web, pull requests merged in 2018-09, with the labels that each got.

#232 Revert "fix(deps): update dependency react-router to v4"
  package-lock.json
  package.json
  renovate.json
Labels: bug

#243 Styles ReactToastify v4
  src/index.tsx
Labels: bug

#263 Upgrade Webpack and Webpack-dev-server
  devServer.js
  package-lock.json
  package.json
  renovate.json
  webpack.config.js
Labels: feature, security

#236 Toggle Mainnet/Testnet
  devServer.js
  package-lock.json
  package.json
  renovate.json
  src/actions/index.ts
  src/components/atoms/ToggleMainnet/ToggleMainnet.test.tsx
  src/components/atoms/ToggleMainnet/ToggleMainnet.tsx
  src/components/atoms/ToggleRP/ToggleRP.tsx
  src/components/containers/CreateToken.container.test.tsx
  src/components/containers/CreateToken.container.tsx
  src/components/containers/Dashboard.container.tsx
  src/components/containers/ToggleNetwork.container.tsx
  src/components/feature-toggles/features.tsx
  src/components/molecules/CreateToken/CreateToken.scss
  src/components/molecules/CreateToken/CreateToken.tsx
  src/components/templates/DashboardTemplate/DashboardTemplate.tsx
  src/config/features.ts
  src/helpers.ts
  src/index.tsx
  src/interfaces/Props.ts
  src/reducers/ChangeNetworkBitcoin.reducer.ts
  src/reducers/index.ts
  src/sagas/CreateApiToken.saga.ts
  src/typings/react-feature-toggles/index.d.ts
  tests/unit/index.ts
  webpack.config.js
Labels: feature

#281 Staging
  _redirects.staging
  netlify.toml
  webpack.config.js
Labels: infrastructure, team-devops
