Repository poetapp/frost-web, pull requests merged in 2018-11, with the labels that each got.

#364 frost-web for QA
  _redirects.qa
  _redirects.staging
  netlify.toml
  package.json
  webpack.config.js
Labels: infrastructure, refactor, team-devops

#407 remove context from the toml file
  netlify.toml
Labels: bug

#458 Style change
  src/components/atoms/Button/Button.scss
  src/components/atoms/FooterHome/FooterHome.scss
  src/components/atoms/Input/Input.scss
  src/components/atoms/LoadingPage/LoadingPage.scss
  src/components/atoms/NavigationList/NavigationList.scss
  src/components/atoms/TextDisclaimer/TextDisclaimer.scss
  src/components/atoms/ToggleRP/ToggleRP.scss
  src/components/atoms/Tooltip/Tooltip.scss
  src/components/molecules/CreateToken/CreateToken.scss
  src/components/molecules/Forms/SignIn/SignIn.scss
  src/components/molecules/Forms/SignUp/SignUp.scss
  src/components/molecules/Forms/SignUp/SignUp.tsx
  src/components/molecules/HeaderHome/HeaderHome.scss
  src/components/molecules/PanelOptions/PanelOptions.scss
  src/components/pages/Home/Home.layout.tsx
  src/components/pages/Home/Home.style.scss
  src/components/styles/colors.scss
  src/components/styles/reset.scss
  src/components/templates/DashboardTemplate/DashboardTemplate.scss
  src/images/documentation.svg
  src/images/integrations.svg
  src/images/key.svg
  src/images/nokey.svg
Labels: don't merge

#488 fix: Copy to Clipboard Mobile
  package-lock.json
  package.json
  src/components/atoms/CopyableText/CopyableText.scss
  src/components/atoms/CopyableText/CopyableText.tsx
  src/components/atoms/Hash/Hash.scss
  src/components/atoms/Hash/Hash.tsx
  typings/clipboard.d.ts
Labels: bug
